import { 
  BookOpen, FileText, Briefcase, ShieldCheck, 
  Cpu, Award, Zap, Lightbulb, PenTool, 
  Search, Shield, Star, Sparkles, Layout,
  Smartphone, Globe, Database, Terminal,
  Microchip, Cloud, Lock, Settings, BarChart,
  HardDrive, Layers, Box, Activity, Map,
  CheckCircle2, AlertCircle, HelpCircle, Info
} from "lucide-react";

export const ICON_MAP: Record<string, any> = {
  BookOpen,
  FileText,
  Briefcase,
  ShieldCheck,
  Cpu,
  Award,
  Zap,
  Lightbulb,
  PenTool,
  Search,
  Shield,
  Star,
  Sparkles,
  Layout,
  Smartphone,
  Globe,
  Database,
  Terminal,
  Microchip,
  Cloud,
  Lock,
  Settings,
  BarChart,
  HardDrive,
  Layers,
  Box,
  Activity,
  Map,
  CheckCircle2,
  AlertCircle,
  HelpCircle,
  Info
};
