export const SERVICES_DATA: Record<string, any> = {
  "professional-write-ups": { desc: "High-quality, professional technical and academic write-ups tailored to your exact requirements.", price: 5, delivery: "Urgent 1–2 Days · Standard 7–12 Days", fields: { topicLabel: "Topic / Domain", topicPlaceholder: "e.g. Artificial Intelligence in Finance", scopeLabel: "Word Count / Scope", scopePlaceholder: "e.g. 5000 words" }, deliverables: ["Technical Report", "Diagrams Included", "Formatting", "References"] },
  "phd-thesis": { desc: "End-to-end support and drafting for your doctoral research thesis to meet university standards.", price: 20000, delivery: "Urgent 15–20 Days · Standard 30–45 Days", fields: { topicLabel: "Thesis Topic / Domain", topicPlaceholder: "e.g. Machine Learning in Healthcare", scopeLabel: "Word Count / Chapters", scopePlaceholder: "e.g. 5 Chapters, 20k words" }, deliverables: ["Full Thesis", "Turnitin + AI Plag Report", "PPT Presentation", "Source Code"] },
  "research-paper": { desc: "High-quality research papers ready for IEEE, Scopus, or other major journals.", price: 2700, delivery: "Urgent 2–5 Days · Standard 12–20 Days", fields: { topicLabel: "Paper Topic / Domain", topicPlaceholder: "e.g. AI-Powered Stethoscope", scopeLabel: "Word Count / Page Count", scopePlaceholder: "e.g. 15k words or 50 pages" }, deliverables: ["Journal Paper", "Turnitin + AI Plag Report", "PPT Presentation", "Source Code", "Submission Help"] },
  "final-year-report": { desc: "Professional project reports, technical manuals, and documentation for your final year. Soft copy delivered.", price: 1000, delivery: "Urgent 1–3 Days · Standard 5–7 Days", fields: { topicLabel: "Project Topic", topicPlaceholder: "e.g. Smart IoT Home System", scopeLabel: "Page Count", scopePlaceholder: "e.g. 50-60 pages" }, deliverables: ["Project Report (Soft Copy)", "Turnitin + AI Plag Report", "PPT Presentation", "Source Code"] },
  "design-patent": { desc: "Protect the unique visual look and feel of your invention with official registration.", price: 1800, delivery: "Filing Urgent 1–2 Days · Standard 5–12 Days", fields: { topicLabel: "Invention Name", topicPlaceholder: "e.g. Ergonomic Smart Mouse", scopeLabel: "Number of Views / Drawings", scopePlaceholder: "e.g. 7 views (Top, Bottom, etc.)" }, deliverables: ["Technical Drawings", "Application Forms", "Government Filing", "Status Tracking"] },
  "utility-patent": { desc: "Technical drafting and claims architecture for your functional engineering inventions.", price: 35000, delivery: "Filing Urgent 12–20 Days · Standard 21–30 Days", fields: { topicLabel: "Invention Concept", topicPlaceholder: "e.g. Novel drone stabilization method", scopeLabel: "Number of Claims / Complexity", scopePlaceholder: "e.g. 10 claims, 3 diagrams" }, deliverables: ["Patent Draft", "Technical Diagrams", "Prior Art Search", "Government Filing"] },
  "copyright": { desc: "Officially register your software, logo, creative work, or source code with the Indian Copyright Office.", price: 2000, delivery: "Filing in 2 Days · Grant depends on Government (up to 30–45 Days)", fields: { topicLabel: "Title of Your Work", topicPlaceholder: "e.g. KalvexBot Mobile App", scopeLabel: "Description of Work", scopePlaceholder: "e.g. Android application with 12,000 lines of Java code" }, deliverables: ["Copyright Application (Form XIV)", "Government Filing", "Diary Number", "Digital Certificate", "Hard Copy Submission"] },
  "trademark": { desc: "Register your startup logo, brand name, or tagline across India securely.", price: 10000, delivery: "6–12 Months (Filing in 3 Days)", fields: { topicLabel: "Brand Name / Logo Description", topicPlaceholder: "e.g. 'KALVEX' Wordmark", scopeLabel: "Business Classes", scopePlaceholder: "e.g. Class 9 and 42" }, deliverables: ["Trademark Search", "Application Forms", "Government Filing", "Status Tracking"] },
  "mini-project": { desc: "Pre-built or custom mini-projects featuring high-quality source code and schematics.", price: 2100, delivery: "Urgent 1–3 Days · Standard 7–10 Days", fields: { topicLabel: "Project Concept", topicPlaceholder: "e.g. Bluetooth Home Automation", scopeLabel: "Hardware/Software Requirements", scopePlaceholder: "e.g. Arduino UNO, Android App" }, deliverables: ["Source Code", "Circuit Diagrams", "Project Report", "Working Demo Video"] },
  "major-project": { desc: "Complex final-year engineering projects for CS, Electronics, and Robotics students.", price: 8000, delivery: "Urgent 10–15 Days · Standard 21–30 Days", fields: { topicLabel: "Project Domain / Topic", topicPlaceholder: "e.g. AI Drone for Crop Monitoring", scopeLabel: "Key Technologies", scopePlaceholder: "e.g. Python, YOLOv8, Raspberry Pi" }, deliverables: ["Source Code", "Hardware Implementation", "Project Report", "Research Paper", "PPT Presentation"] },
  "black-book-printing": { desc: "Premium final year black book and bond paper printing services with gold embossing and rapid 1-2 days delivery across Maharashtra.", price: 265, delivery: "1–2 Days (Pan Maharashtra)", fields: { topicLabel: "Project Cover Title", topicPlaceholder: "e.g. Smart IoT Home System", scopeLabel: "Page Count (21 to 120)", scopePlaceholder: "e.g. 45" }, deliverables: ["Gold Embossed Hard Bound Book", "Bond Paper Colour Prints", "1-2 Days Fast Delivery", "Vibrant All Pages Colour"] }
};
